Repository fabric8-analytics/fabric8-analytics-vscode-extension, pull requests merged in 2019-08, with the labels that each got.

#330 fix(transitive): Enable transitive dependency report by default
  src/stackanalysismodule.ts
Labels: enable-feature

#333 fix(pypi): Generate pylist.json only if pip install runs without error
  src/ProjectDataProvider.ts
Labels: bug

#334 feat(welcome-msg): Show welcome message after upgrading to latest version
  src/constants.ts
  src/extension.ts
Labels: enhancement

#326 python readme changes
  README.md
Labels: doc
